name: repat_event
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  dart_mappable: ^4.4.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  eva_icons_flutter: ^3.1.0
  fake_cloud_firestore: ^3.1.0
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  get_it: ^8.0.3
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  heroicons: ^0.11.0
  icons_plus: ^5.0.0
  iconsax: ^0.0.8
  intl: ^0.19.0
  ionicons: ^0.2.2
  mockito: ^5.4.5
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.3.1+1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/San-Francisco-Pro-Fonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/San-Francisco-Pro-Fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/San-Francisco-Pro-Fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/San-Francisco-Pro-Fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/San-Francisco-Pro-Fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/San-Francisco-Pro-Fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/San-Francisco-Pro-Fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/San-Francisco-Pro-Fonts/SF-Pro-Display-Thin.otf
          weight: 100
        - asset: assets/fonts/San-Francisco-Pro-Fonts/SF-Pro-Display-Ultralight.otf
          weight: 200
